
def fix_codemirror
  header = "<!-- deck.js extension JS files -->"
  cm = '<script src="deck.js/extensions/codemirror/codemirror.js" type="text/javascript"></script>'
  all = File.read("slides.html")
  all.gsub!(cm, "")
  all.gsub!(header, "#{header}\n#{cm}") 
  File.open("slides.html", "w") { |f| f.write(all) }
end

desc "Generate keydown slides"
task :generate do
  #Bundler.with_clean_env do
  sh "keydown slides slides.md"
  fix_codemirror
end
